workflows:
  ios-unsigned:
    name: Unsigned iOS Build

    environment:
      flutter: 3.10.6

    scripts:
      - flutter clean
      - flutter pub get

      # Podfile KALIR, sorun değil
      - cd ios && pod install && cd ..

      # İMZASIZ BUILD
      - flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
